version: '3'

services:
 php:
   image: jhonoryza/php:ubuntu-7.4-composer-2
   restart: unless-stopped
   volumes:
   - ./:/var/www/html
   user: www-data
 nginx:
   image: jhonoryza/nginx:laravel-alpine
   restart: unless-stopped
   volumes:
   - ./:/var/www/html:ro
   ports:
   - 8002:80
